### ISSUE TITLE
Saliency map prediction

### ISSUE THREAD

**Issue by Salima-Bourbia** [LIDONGgittt/saliency-map-pointnet#1]
Hello,
I would like to access to the weights of your trained model, but unfortunately no access is given.
Thank you.

**Comment by LIDONGgittt** [comment]
Thank you for your interest in my previous work.
Unfortunately, I apologize for not having a copy of the pre-trained model after the online drive has expired. However, you can train your own model, and I assure you that it is not a difficult process.
